name: CI

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12.4"
      - run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - run: python ./generate.py --no-edit --package --debug --output ./build
      - run: |
          python ./archive/kiowhat.py \
            ./missions/CyprusInvasion/json/objectives.json \
            ./missions/CyprusInvasion/json/airbases.json \
            ./missions/CyprusInvasion/json/farps.json \
            ./build/OH58D-MissionData/CyprusInvasion
      - run: |
          python ./archive/kiowhat.py \
            ./missions/RockTheCasbah/json/objectives.json \
            ./missions/RockTheCasbah/json/airbases.json \
            ./missions/RockTheCasbah/json/farps.json \
            ./build/OH58D-MissionData/RockTheCasbah
      - run: |
          python ./archive/kiowhat.py \
            ./missions/DangerZone/json/objectives.json \
            ./missions/DangerZone/json/airbases.json \
            ./missions/DangerZone/json/farps.json \
            ./build/OH58D-MissionData/DangerZone \
            --carriers_file ./missions/DangerZone/json/carriers.json
      - run: |
          python ./archive/kiowhat.py \
            ./missions/BalloonFight/json/objectives.json \
            ./missions/BalloonFight/json/airbases.json \
            ./missions/BalloonFight/json/farps.json \
            ./build/OH58D-MissionData/BalloonFight
      - uses: actions/upload-artifact@v4
        with:
          name: missions
          path: ./build
      - run: cd ./build && zip -r OH58D-MissionData.zip ./OH58D-MissionData
      - uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            ./build/**/*.miz
            ./build/OH58D-MissionData.zip
